### ISSUE TITLE
Anax di should use configure/configuretrait instead of common/configuretrait

### ISSUE THREAD

**Issue by MagnusGreiff** [canax/di#1]
Anax di should use configure/configuretrait instead of common/configuretrait. common/configuretrait can not handle direct path.

**Comment by mosbth** [comment]
Check if you have the latest version of `anax/di`. It seems the change is already there.

**Comment by MagnusGreiff** [comment]
I use version 1.0.8.
From composer show: anax/di  v1.0.8  Anax dependency injection module.

**Comment by mosbth** [comment]
Fixed in anax/url, already fixed here.
